name: Publish to PyPI
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
env:
  TWINE_USERNAME: ${{ secrets.PYPI_API_USER }}
  TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '>=3.8'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install build twine
      - name: Build package
        run: python -m build
      - name: Publish package
        run: twine upload dist/*
