name: Build and Publish to PyPI
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ">=3.8"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install build
      - name: Build wheel
        run: python -m build --wheel
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: autolv_dist
          path: dist
          if-no-files-found: error
  publish:
    needs: [build]
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - uses: actions/download-artifact@v3
        with:
          name: autolv_dist
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
